#!/bin/bash

#Run this script as : "source /path/script" for the "gnome-terminal &" part to work

simoptimum=0

while [ $simoptimum -eq 0 ]
do
	sleep 10

	cp ~/Desktop/Project\ with\ Prof.\ Anosh/Codes/Code\ 13-10/code/matrixmodel/data/jvals{,.bkp}

	awk '{for(i=1;i<=NF;i++) {sum[i] += $i; sumsq[i] += ($i)^2}} END {for (i=1;i<=NF;i++) { avg=sum[i]/NR; sd=sqrt((sumsq[i]-sum[i]^2/NR)/NR)}} END {avg = avg/4;if (sd<avg) printf "IFTERMINATE=\42%d\42\n",1; else printf "IFTERMINATE=\42%d\42\n",0;}' ~/Desktop/Project\ with\ Prof.\ Anosh/Codes/Code\ 13-10/code/matrixmodel/data/jvals >> ~/Desktop/Project\ with\ Prof.\ Anosh/Codes/Code\ 13-10/code/matrixmodel/data/ifterminate

	CHECK=1

	source ~/Desktop/Project\ with\ Prof.\ Anosh/Codes/Code\ 13-10/code/matrixmodel/data/ifterminate

	if ((  $IFTERMINATE == $CHECK )); then

		beep
		sleep 1
		beep
		sleep 1
		beep

 		gnome-terminal &
 		kill -9 $PPID

 		simoptimum=1

# 		rm ~/Desktop/Project\ with\ Prof.\ Anosh/Codes/Code\ 13-10/code/matrixmodel/data/jvals

# 		mv ~/Desktop/Project\ with\ Prof.\ Anosh/Codes/Code\ 13-10/code/matrixmodel/data/jvals.bkp ~/Desktop/Project\ with\ Prof.\ Anosh/Codes/Code\ 13-10/code/matrixmodel/data/jvals

# 		rm ~/Desktop/Project\ with\ Prof.\ Anosh/Codes/Code\ 13-10/code/matrixmodel/data/ifterminate

	else

		printf "No optimum yet.\n"
#		rm ~/Desktop/Project\ with\ Prof.\ Anosh/Codes/Code\ 13-10/code/matrixmodel/data/ifterminate
#		rm ~/Desktop/Project\ with\ Prof.\ Anosh/Codes/Code\ 13-10/code/matrixmodel/data/jvals.bkp



	fi
done

